sudo: true
dist: trusty
language: rust

addons:
  apt:
    sources:
      - sourceline: 'ppa:pinepain/libv8-5.4'
      - ubuntu-toolchain-r-test
    packages:
      # Modern compilers
      - gcc-6
      - g++-6
      # The V8 version that we want to bind
      - libv8-5.4-dev
      # Dependencies for travis-cargo and for coverage
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

env:
  global:
    - CC=gcc-6
    - CXX=g++-6

matrix:
  include:
    - env: FEATURES=""
    - env: FEATURES="--features=shared"

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build -- $FEATURES --manifest-path=v8-sys/Cargo.toml &&
      travis-cargo test -- $FEATURES --manifest-path=v8-sys/Cargo.toml &&
      travis-cargo bench -- $FEATURES --manifest-path=v8-sys/Cargo.toml &&
      travis-cargo build -- $FEATURES &&
      travis-cargo test -- $FEATURES &&
      travis-cargo bench -- $FEATURES

after_success:
  - travis-cargo coveralls --no-sudo --verify
