sudo: false
language: rust

addons:
  apt:
    sources:
      - sourceline: 'ppa:pinepain/libv8-5.4'
      - ubuntu-toolchain-r-test
    packages:
      # Modern compilers
      - gcc-6
      - g++-6
      # The V8 version that we want to bind
      - libv8-dev
      # Dependencies for travis-cargo and for coverage
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build -- --manifest-path=v8-sys/Cargo.toml &&
      travis-cargo test -- --manifest-path=v8-sys/Cargo.toml &&
      travis-cargo bench -- --manifest-path=v8-sys/Cargo.toml &&
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench

after_success:
  - travis-cargo coveralls --no-sudo --verify
