[package]
authors = ["David Flemström <dflemstr@spotify.com>"]
name = "v8"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.1"

[dependencies.v8-sys]
path = "v8-sys"

[features]
shared = ["v8-sys/shared"]
